<#
.SYNOPSIS
  Generate ../story.js (the 14-scene story for the motion demo) from the v0 fixture ../../fixtures/session.json.

.DESCRIPTION
  The motion demo keeps its own snapshot of the story so it never imports a v0 file. Rerun this script whenever
  the fixture changes, then re-check durations. It only reads the fixture; it never writes outside story.js.

.EXAMPLE
  .\make-story.ps1
#>
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$fixture = (Resolve-Path (Join-Path $root '..\fixtures\session.json')).Path
$j = Get-Content -Raw -Encoding UTF8 $fixture | ConvertFrom-Json

$scenes = @(); $start = 0.0; $n = 0
foreach ($e in $j.timeline) {
  $n++
  $v = $e.visual
  $vs = $j.visual_scenes.($v.scene)
  $dur = [double]$e.duration_ms / 1000
  $blueLines = @(); if ($v.blue_code_active) { $blueLines = @($e.public_activity.blue) }
  $scenes += [ordered]@{
    id = $v.scene; n = $n; num = ('{0:00}' -f $n)
    title = $e.title; label = $vs.label; alt = $vs.alt
    file = (Split-Path $vs.backdrop -Leaf)
    start = $start; dur = $dur
    phase = $v.phase; actor = $e.actor; summary = $e.summary
    red = ($v.red_status -replace 'Scripted action', 'Demo action' -replace 'Story: ', '')
    blue = ($v.blue_status -replace 'Scripted action', 'Demo action')
    bank = $v.bank; alarm = [bool]$v.alarm
    redCheck = [bool]$v.red_check; blueCheck = [bool]$v.blue_check; blueCode = [bool]$v.blue_code_active
    vaultDoor = $v.vault_door; screen = $vs.screen
    redLines = @($e.public_activity.red); blueLines = $blueLines
  }
  $start += $dur
}

$obj = [ordered]@{ source = 'fixtures/session.json'; fixtureVersion = $j.version; sessionId = $j.session_id; total = $start; scenes = $scenes }
$json = ConvertTo-Json -InputObject $obj -Depth 8
$js = "// Generated by tools/make-story.ps1 from ../fixtures/session.json. Do not edit by hand; rerun the script when the fixture changes.`n" +
      "// A snapshot of the v0 story, so this page never imports a v0 file.`nwindow.MP_STORY = $json;`n"
[IO.File]::WriteAllText((Join-Path $root 'story.js'), $js, (New-Object Text.UTF8Encoding $false))
"wrote story.js: $($scenes.Count) scenes, total $start s"
$scenes | ForEach-Object { '  {0} {1,-11} {2,6:N1}s  start {3,5:N1}  bank {4,-10} alarm {5,-5} blueCode {6}' -f $_.num, $_.id, $_.dur, $_.start, $_.bank, $_.alarm, $_.blueCode }
