// Generated by tools/make-story.ps1 from ../fixtures/session.json. Do not edit by hand; rerun the script when the fixture changes.
// A snapshot of the v0 story, so this page never imports a v0 file.
window.MP_STORY = {
    "source":  "fixtures/session.json",
    "fixtureVersion":  "0.1.0",
    "sessionId":  "rowdyhacks26-demo-v0",
    "total":  85.5,
    "scenes":  [
                   {
                       "id":  "driver",
                       "n":  1,
                       "num":  "01",
                       "title":  "The getaway begins",
                       "label":  "01 / Choose the route",
                       "alt":  "Your original driver viewpoint, route map and Start graphic are preserved.",
                       "file":  "01_driver_start.png",
                       "start":  0,
                       "dur":  3,
                       "phase":  "Ready",
                       "actor":  "Session",
                       "summary":  "Choose the route and begin the nighttime heist.",
                       "red":  "Ready",
                       "blue":  "Standby",
                       "bank":  "ONLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  false,
                       "blueCode":  false,
                       "vaultDoor":  null,
                       "screen":  null,
                       "redLines":  [
                                        "// public fixture feed",
                                        "state = \"ready\";"
                                    ],
                       "blueLines":  [

                                     ]
                   },
                   {
                       "id":  "crash",
                       "n":  2,
                       "num":  "02",
                       "title":  "Through the front doors",
                       "label":  "02 / Through the front doors",
                       "alt":  "The same red hatchback breaks through the closed double doors of the bank at night.",
                       "file":  "02_bank_crash.png",
                       "start":  3,
                       "dur":  4.5,
                       "phase":  "Entry",
                       "actor":  "Red Operator",
                       "summary":  "The red hatchback breaks through the bank’s closed entrance.",
                       "red":  "Entering",
                       "blue":  "Standby",
                       "bank":  "ONLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  false,
                       "blueCode":  false,
                       "vaultDoor":  null,
                       "screen":  null,
                       "redLines":  [
                                        "// public fixture feed",
                                        "state = \"ready\";"
                                    ],
                       "blueLines":  [

                                     ]
                   },
                   {
                       "id":  "entry",
                       "n":  3,
                       "num":  "03",
                       "title":  "The vault ahead",
                       "label":  "03 / The vault in the distance",
                       "alt":  "Red stands inside the damaged entrance and looks down the long lobby toward the distant closed vault. The red car has been removed from the doorway view.",
                       "file":  "03_bank_entry-r2.png",
                       "start":  7.5,
                       "dur":  5,
                       "phase":  "Inside the bank",
                       "actor":  "Red Scout",
                       "summary":  "Inside the lobby, the robber heads toward the vault.",
                       "red":  "Approaching vault",
                       "blue":  "Standby",
                       "bank":  "ONLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  false,
                       "blueCode":  false,
                       "vaultDoor":  null,
                       "screen":  null,
                       "redLines":  [
                                        "// public fixture feed",
                                        "state = \"ready\";"
                                    ],
                       "blueLines":  [

                                     ]
                   },
                   {
                       "id":  "vault",
                       "n":  4,
                       "num":  "04",
                       "title":  "Red takes the website down",
                       "label":  "04 / At the keypad",
                       "alt":  "Red uses the keypad beside the closed vault. The enlarged website screen dominates the wall; the separate Red code screen below it is much smaller. The displayed website is straight and level.",
                       "file":  "04_large_straight_website-r4.png",
                       "start":  12.5,
                       "dur":  12,
                       "phase":  "Red activity",
                       "actor":  "Red Operator",
                       "summary":  "The bank website is available while Red’s simulated action runs.",
                       "red":  "Attempt in progress",
                       "blue":  "Standby",
                       "bank":  "ONLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  false,
                       "blueCode":  false,
                       "vaultDoor":  "closed",
                       "screen":  "vault",
                       "redLines":  [
                                        "// RED · DEMO ACTIVITY",
                                        "target = \"bank-lab-demo\";",
                                        "attempt.status = \"running\";",
                                        "traffic.state = \"simulated\";",
                                        "availability = \"degrading\";",
                                        "// waiting for scene result"
                                    ],
                       "blueLines":  [

                                     ]
                   },
                   {
                       "id":  "alarm",
                       "n":  5,
                       "num":  "05",
                       "title":  "Website offline · vault open",
                       "label":  "05 / Alarm · Bank Lab goes dark",
                       "alt":  "The vault is now open. The larger website display goes black, the small Red screen shows a green completion check, and the alarm glows red.",
                       "file":  "05_open_vault_matched-r3.png",
                       "start":  24.5,
                       "dur":  6.5,
                       "phase":  "Simulated interruption",
                       "actor":  "Bank Lab",
                       "summary":  "The website goes dark, the vault opens, and Red’s scripted action completes.",
                       "red":  "Demo action complete",
                       "blue":  "Alert pending",
                       "bank":  "OFFLINE",
                       "alarm":  true,
                       "redCheck":  true,
                       "blueCheck":  false,
                       "blueCode":  false,
                       "vaultDoor":  "open",
                       "screen":  "vault",
                       "redLines":  [
                                        "// public fixture feed",
                                        "action.status = \"scripted_complete\";",
                                        "// No private plan or attack code"
                                    ],
                       "blueLines":  [

                                     ]
                   },
                   {
                       "id":  "dispatch",
                       "n":  6,
                       "num":  "06",
                       "title":  "Blue receives the alert",
                       "label":  "06 / Alert from marked street area",
                       "alt":  "Blue receives the alarm from inside the cop car at the marked end of the street, facing back down the road toward the bank ahead on the left.",
                       "file":  "06_car_orientation-r9.png",
                       "start":  31,
                       "dur":  6.5,
                       "phase":  "Blue alert",
                       "actor":  "Blue Monitor",
                       "summary":  "Blue receives the bank alarm from the approaching patrol car.",
                       "red":  "Inside bank",
                       "blue":  "Alert received",
                       "bank":  "OFFLINE",
                       "alarm":  true,
                       "redCheck":  false,
                       "blueCheck":  false,
                       "blueCode":  false,
                       "vaultDoor":  null,
                       "screen":  "car",
                       "redLines":  [
                                        "// public fixture feed",
                                        "action.status = \"scripted_complete\";",
                                        "// No private plan or attack code"
                                    ],
                       "blueLines":  [

                                     ]
                   },
                   {
                       "id":  "money",
                       "n":  7,
                       "num":  "07",
                       "title":  "Into the vault",
                       "label":  "07 / Fill the bag",
                       "alt":  "The robber fills the cloth money bag fully inside the vault chamber, surrounded by storage shelves. No vault door, doorway or corridor is visible.",
                       "file":  "07_inside_vault_money-r2.png",
                       "start":  37.5,
                       "dur":  4.5,
                       "phase":  "Heist illustration",
                       "actor":  "Story",
                       "summary":  "Inside the vault, the robber fills a bag with money.",
                       "red":  "collecting money",
                       "blue":  "Responding",
                       "bank":  "OFFLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  false,
                       "blueCode":  false,
                       "vaultDoor":  null,
                       "screen":  null,
                       "redLines":  [
                                        "// public fixture feed",
                                        "action.status = \"scripted_complete\";",
                                        "// No private plan or attack code"
                                    ],
                       "blueLines":  [

                                     ]
                   },
                   {
                       "id":  "exit",
                       "n":  8,
                       "num":  "08",
                       "title":  "Spotted at the entrance",
                       "label":  "08 / Blue arrives in the distance",
                       "alt":  "Red emerges from the damaged bank entrance and notices a distant approaching police car.",
                       "file":  "08_bank_exit.png",
                       "start":  42,
                       "dur":  4.5,
                       "phase":  "Exit",
                       "actor":  "Story",
                       "summary":  "The robber leaves the bank and spots the approaching patrol car.",
                       "red":  "Leaving",
                       "blue":  "Approaching",
                       "bank":  "OFFLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  false,
                       "blueCode":  false,
                       "vaultDoor":  null,
                       "screen":  null,
                       "redLines":  [
                                        "// public fixture feed",
                                        "action.status = \"scripted_complete\";",
                                        "// No private plan or attack code"
                                    ],
                       "blueLines":  [

                                     ]
                   },
                   {
                       "id":  "rush",
                       "n":  9,
                       "num":  "09",
                       "title":  "Back to the car",
                       "label":  "09 / Back to the hatchback",
                       "alt":  "Red rushes from the bank steps to the open driver door of the red hatchback, preserving scene 08\u0027s parking spot beside the bank and its street viewpoint.",
                       "file":  "09_rush_same_parking-r2.png",
                       "start":  46.5,
                       "dur":  4,
                       "phase":  "Escape",
                       "actor":  "Story",
                       "summary":  "The robber rushes to the red hatchback beside the bank.",
                       "red":  "Returning to car",
                       "blue":  "Arriving",
                       "bank":  "OFFLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  false,
                       "blueCode":  false,
                       "vaultDoor":  null,
                       "screen":  null,
                       "redLines":  [
                                        "// public fixture feed",
                                        "action.status = \"scripted_complete\";",
                                        "// No private plan or attack code"
                                    ],
                       "blueLines":  [

                                     ]
                   },
                   {
                       "id":  "mirror",
                       "n":  10,
                       "num":  "10",
                       "title":  "Blue in the mirror",
                       "label":  "10 / Blue in the rear-view mirror",
                       "alt":  "Red is back at the wheel, and the police car is visible behind him in the rear-view mirror.",
                       "file":  "10_rear_view.png",
                       "start":  50.5,
                       "dur":  4.5,
                       "phase":  "Pursuit starts",
                       "actor":  "Story",
                       "summary":  "The police car appears in the getaway car’s rear-view mirror.",
                       "red":  "Driving",
                       "blue":  "Following",
                       "bank":  "OFFLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  false,
                       "blueCode":  false,
                       "vaultDoor":  null,
                       "screen":  null,
                       "redLines":  [
                                        "// public fixture feed",
                                        "action.status = \"scripted_complete\";",
                                        "// No private plan or attack code"
                                    ],
                       "blueLines":  [

                                     ]
                   },
                   {
                       "id":  "pursuit",
                       "n":  11,
                       "num":  "11",
                       "title":  "The chase · Blue rebuilds",
                       "label":  "11 / Pursuit · recovery in progress",
                       "alt":  "Blue\u0027s car viewpoint follows the red hatchback along the city street, away from the bank. More cabin and a much larger dashboard display are visible.",
                       "file":  "11_blue_pursuit.png",
                       "start":  55,
                       "dur":  13,
                       "phase":  "Blue recovery",
                       "actor":  "Blue Defender",
                       "summary":  "Blue works on recovery as the pursuit heads along the city street.",
                       "red":  "Driving",
                       "blue":  "Recovery action applied",
                       "bank":  "RECOVERING",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  false,
                       "blueCode":  true,
                       "vaultDoor":  null,
                       "screen":  "car",
                       "redLines":  [
                                        "// public fixture feed",
                                        "action.status = \"scripted_complete\";",
                                        "// No private plan or attack code"
                                    ],
                       "blueLines":  [
                                         "// BLUE · DEMO RECOVERY",
                                         "incident.status = \"accepted\";",
                                         "service.config = \"restored\";",
                                         "recovery.status = \"applied\";",
                                         "health.check = \"pending\";",
                                         "// awaiting demo health event"
                                     ]
                   },
                   {
                       "id":  "recovered",
                       "n":  12,
                       "num":  "12",
                       "title":  "Website restored",
                       "label":  "12 / Blue\u0027s scripted recovery completes",
                       "alt":  "The same pursuit viewpoint is retained; the enlarged Blue display switches to a green completion check.",
                       "file":  "12_blue_recovery_complete.png",
                       "start":  68,
                       "dur":  6.5,
                       "phase":  "Recovery reported",
                       "actor":  "Blue Defender",
                       "summary":  "The demo reports restored website availability and Blue’s completion screen.",
                       "red":  "Driving",
                       "blue":  "Demo action complete",
                       "bank":  "ONLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  true,
                       "blueCode":  true,
                       "vaultDoor":  null,
                       "screen":  "car",
                       "redLines":  [
                                        "// public fixture feed",
                                        "action.status = \"scripted_complete\";",
                                        "// No private plan or attack code"
                                    ],
                       "blueLines":  [
                                         "// public fixture feed",
                                         "recovery.status = \"scripted_complete\";",
                                         "bank.observed = \"online\";"
                                     ]
                   },
                   {
                       "id":  "hydroplane",
                       "n":  13,
                       "num":  "13",
                       "title":  "Rain changes the chase",
                       "label":  "13 / Rain · loss of traction",
                       "alt":  "The red hatchback hydroplanes into the light pole in the same Blue car viewpoint. The dashboard completion check matches scene 12\u0027s larger size.",
                       "file":  "13_hydroplane_check-r2.png",
                       "start":  74.5,
                       "dur":  4.5,
                       "phase":  "Street crash",
                       "actor":  "Story",
                       "summary":  "The red hatchback hydroplanes into a light pole on the wet street.",
                       "red":  "vehicle stopped",
                       "blue":  "Stopping",
                       "bank":  "ONLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  true,
                       "blueCode":  true,
                       "vaultDoor":  null,
                       "screen":  "car",
                       "redLines":  [
                                        "// public fixture feed",
                                        "action.status = \"scripted_complete\";",
                                        "// No private plan or attack code"
                                    ],
                       "blueLines":  [
                                         "// public fixture feed",
                                         "recovery.status = \"scripted_complete\";",
                                         "bank.observed = \"online\";"
                                     ]
                   },
                   {
                       "id":  "arrest",
                       "n":  14,
                       "num":  "14",
                       "title":  "End of the road",
                       "label":  "14 / The street arrest",
                       "alt":  "Blue arrests the uninjured Red robber on the same street beside the stopped cars.",
                       "file":  "14_street_arrest.png",
                       "start":  79,
                       "dur":  6.5,
                       "phase":  "Story complete",
                       "actor":  "Story",
                       "summary":  "Blue arrests the robber beside the stopped cars. The demo story is complete.",
                       "red":  "Story complete",
                       "blue":  "Story complete",
                       "bank":  "ONLINE",
                       "alarm":  false,
                       "redCheck":  false,
                       "blueCheck":  true,
                       "blueCode":  true,
                       "vaultDoor":  null,
                       "screen":  null,
                       "redLines":  [
                                        "// public fixture feed",
                                        "action.status = \"scripted_complete\";",
                                        "// No private plan or attack code"
                                    ],
                       "blueLines":  [
                                         "// public fixture feed",
                                         "recovery.status = \"scripted_complete\";",
                                         "bank.observed = \"online\";"
                                     ]
                   }
               ]
};
